### ISSUE TITLE
Tomorrow = null

### ISSUE THREAD

**Issue by labaland** [TekniskSupport/home-assistant-python-script#1]
Sensor breaks when tomorrow is "null"

**Comment by TekniskSupport** [comment]
example call code (but you should use three different sensors, to populate with data)

entity_id: sensor.nordpool_kwh_se1_sek_4_10_025
target_entity_id: input_text.nordpol_priser
today_entity_id: input_text.nordpol_priser
tomorrow_entity_id: input_text.nordpol_priser
today: today
tomorrow: tomorrow
hours: 3
